let newId = 222;

function id() {
    return newId++;
}
// сюда можно добаить больше инфы



const HTML_CSS = [
    "Настройка окружения, основы Git",
    "Базовая разметка и структура HTML-страницы",
    "Все основные HTML теги",
    "Знакомство с CSS и стилями для текста, единицы измерения",
    "Свойства display (flex,block,inline-block)..",
    "CSS-свойства (margin, padding, box-shadow)",
    "Position (absolute, relative, static)..",
    "Свойства grid",
    "Адаптивная верстка, подключение шрифтов",
    "Анимация (burger menu)",
    "Работа над ошибками",
    "Анимация для(hover,focus,active)",
    "Анимация (burger menu)",
    "Продвинутая анимация",
    "Анимация титров",
    'Параллакс анимация',
    "Работа над ошибками (создание резюме для работы)",
]

const CSSAdvanced = [
    "Настройка окружения, основы Git, вспоминаем CSS",
    "Анимация для(hover,focus,active)",
    "Анимация (burger menu)",
    "Продвинутая анимация",
    "Анимация титров",
    'Параллакс анимация',
    "Работа над ошибками (создание резюме для работы)",

]
const CSS_simple = [
    "Настройка окружения, основы Git",
    "Знакомство с CSS и стилями для текста, единицы измерения",
    "Свойства display (flex,block,inline-block)..",
    "CSS-свойства (margin, padding, box-shadow)",
    "Position (absolute, relative, static)..",
    "Свойства grid",
    "Адаптивная верстка, подключение шрифтов",
    "Анимация (burger menu)",
    "Работа над ошибками (создание резюме для работы)",
    
]

const JS = [
    'Знакомство с Javascript , тип данных',
    "Свойства тегов HTML, основы Git",
    "Первое событие, поверхностное знакомство с function",
    'Оператор if else',
    'Оператор switch',
    'Тернарные  операторы',
    'Работа с формой в Js',
    'Цикл while (do while)',
    'Цикл for (Вложеные циклы)',
    'Declaration функции',
    'Expression функции (Самовызывающаяся функция)',
    "Основы массивов",
    "Основные методы массивов",
    'Методы массивов',
    'Взаимодействие методов между собой',
    'Основы объектов',
    "Певый мини проект (Взаимодействие массивов и объектов)",
    "LocalStorage и sessionStorage",
    "События мышки",
    "События клавиатуры",
    'Тач события',
    "Мини проект событий",
    "Слайдер",
    "Фильтр текста",
    "Магазинный фильтр",
    "Regex",
    'Замыкание и Рекурсия',
    "This, apply,call,bind, proto, prototype",
    "class, constructor, cuper",
    "работа с  Api (асинхронный код)",
    'Полноценный проект (Пишем свой Google на js) часть 1',
    'Полноценный проект (Пишем свой Google на js) часть 2',
    'Полноценный проект (Пишем свой Google на js) часть 3',
    "Работа над ошибками (создание резюме для работы)",
    
    
    
]
const React = [
    "Вспоминаем основы js (Git)",
    "Regex",
    'Замыкание и Рекурсия',
    "This, apply,call,bind, proto, prototype",
    "class, constructor, cuper",
    "работа с  Api (асинхронный код)",
    "Знакомство с React (насройка окружения)",
    "React компоненты и props",
    "Первый хук, useState",
    "useMemo",
    "react router dom (Начинаем первый проект, пишем свою социальная сеть)",
    "useEffect и axios",
    "HOC",
    "useContext",
    "Знакомство с разными библиотеками для React",
    "Login (авторегистрация)",
    "Взаимодействие разных аккаунтов вашей соц сети",
    "Отправка локальных фото в сеть (axios post,put...)",
    "Создаем чат между пользователями часть 1",
    "Создаем чат между пользователями часть 2",
    "Создаем чат между пользователями часть 3",
    "Работа над ошибками (создание резюме для работы)",
//Кр сделать компоненту настройки

]

const FrontEnd = [
    "Базовая разметка и структура HTML-страницы",
    "Все основные HTML теги",
    "Знакомство с CSS и стилями для текста, единицы измерения",
    "Свойства display (flex,block,inline-block)..",
    "CSS-свойства (margin, padding, box-shadow)",
    "Position (absolute, relative, static)..",
    "Свойства grid",
    "Адаптивная верстка, подключение шрифтов",
    "Анимация (burger menu)",
    "Продвинутая анимация",
    'Параллакс анимация',
    "Работа над ошибками",
    'Знакомство с Javascript , тип данных',
    "Свойства тегов HTML, основы Git",
    "Первое событие, поверхностное знакомство с function",
    'Оператор if else',
    'Оператор switch',
    'Тернарные  операторы',
    'Работа с формой в Js',
    'Цикл while (do while)',
    'Цикл for (Вложеные циклы)',
    'Declaration функции',
    'Expression функции (Самовызывающаяся функция)',
    "Основы массивов",
    "Основные методы массивов",
    'Методы массивов',
    'Взаимодействие методов между собой',
    'Основы объектов',
    "Певый мини проект (Взаимодействие массивов и объектов)",
    "LocalStorage и sessionStorage",
    "События мышки",
    "События клавиатуры",
    'Тач события',
    "Мини проект событий",
    "Слайдер",
    "Фильтр текста",
    "Магазинный фильтр",
    "Regex",
    'Замыкание и Рекурсия',
    "This, apply,call,bind, proto, prototype",
    "class, constructor, cuper",
    "работа с  Api (асинхронный код)",
    'Полноценный проект (Пишем свой Google на js) часть 1',
    'Полноценный проект (Пишем свой Google на js) часть 2',
    'Полноценный проект (Пишем свой Google на js) часть 3',
    "Работа над ошибками",
    "Regex",
    'Замыкание и Рекурсия',
    "This, apply,call,bind, proto, prototype",
    "class, constructor, cuper",
    "работа с  Api (асинхронный код)",
    "Знакомство с React (насройка окружения)",
    "React компоненты и props",
    "Первый хук, useState",
    "useMemo",
    "react router dom (Начинаем первый проект, пишем свою социальная сеть)",
    "useEffect и axios",
    "HOC",
    "useContext",
    "Знакомство с разными библиотеками для React",
    "Login (авторегистрация)",
    "Взаимодействие разных аккаунтов вашей соц сети",
    "Отправка локальных фото в сеть (axios post,put...)",
    "Создаем чат между пользователями часть 1",
    "Создаем чат между пользователями часть 2",
    "Создаем чат между пользователями часть 3",
    "Работа над ошибками",
    "Знакомство с Redux (mapStateToProps)", //переписываем в редакс
    "action for Redux", // функции для редакс
    "react router dom, HOC, REST API", //Coin и запросы 
    "Знакомство с разными библиотеками для React", //Coincurrent библиотека графика Chart.js
    "Redux, axios, useEffect", // переписываем запросы для redux
    "Login (авторегистрация)", // аторегистрация для редакс
    "библиотека localforage для Redux", // делаем избраное для Coin
    "Создаем чат между пользователями часть 1",
    "Создаем чат между пользователями часть 2",
    "Создаем чат между пользователями часть 3",
    "Работа над ошибками (создание резюме для работы)",
    
]

const FullStack = [
    "Базовая разметка и структура HTML-страницы",
    "Все основные HTML теги",
    "Знакомство с CSS и стилями для текста, единицы измерения",
    "Свойства display (flex,block,inline-block)..",
    "CSS-свойства (margin, padding, box-shadow)",
    "Position (absolute, relative, static)..",
    "Свойства grid",
    "Адаптивная верстка, подключение шрифтов",
    "Анимация (burger menu)",
    "Продвинутая анимация",
    'Параллакс анимация',
    "Работа над ошибками",
    'Знакомство с Javascript , тип данных',
    "Свойства тегов HTML, основы Git",
    "Первое событие, поверхностное знакомство с function",
    'Оператор if else',
    'Оператор switch',
    'Тернарные  операторы',
    'Работа с формой в Js',
    'Цикл while (do while)',
    'Цикл for (Вложеные циклы)',
    'Declaration функции',
    'Expression функции (Самовызывающаяся функция)',
    "Основы массивов",
    "Основные методы массивов",
    'Методы массивов',
    'Взаимодействие методов между собой',
    'Основы объектов',
    "Певый мини проект (Взаимодействие массивов и объектов)",
    "LocalStorage и sessionStorage",
    "События мышки",
    "События клавиатуры",
    'Тач события',
    "Мини проект событий",
    "Слайдер",
    "Фильтр текста",
    "Магазинный фильтр",
    "Regex",
    'Замыкание и Рекурсия',
    "This, apply,call,bind, proto, prototype",
    "class, constructor, cuper",
    "работа с  Api (асинхронный код)",
    'Полноценный проект (Пишем свой Google на js) часть 1',
    'Полноценный проект (Пишем свой Google на js) часть 2',
    'Полноценный проект (Пишем свой Google на js) часть 3',
    "Работа над ошибками",
    "Regex",
    'Замыкание и Рекурсия',
    "This, apply,call,bind, proto, prototype",
    "class, constructor, cuper",
    "работа с  Api (асинхронный код)",
    "Знакомство с React (насройка окружения)",
    "React компоненты и props",
    "Первый хук, useState",
    "useMemo",
    "react router dom (Начинаем первый проект, пишем свою социальная сеть)",
    "useEffect и axios",
    "HOC",
    "useContext",
    "Знакомство с разными библиотеками для React",
    "Login (авторегистрация)",
    "Взаимодействие разных аккаунтов вашей соц сети",
    "Отправка локальных фото в сеть (axios post,put...)",
    "Создаем чат между пользователями часть 1",
    "Создаем чат между пользователями часть 2",
    "Создаем чат между пользователями часть 3",
    "Работа над ошибками",
    "Знакомство с Redux (mapStateToProps)", //переписываем в редакс
    "action for Redux", // функции для редакс
    "react router dom, HOC, REST API", //Coin и запросы 
    "Знакомство с разными библиотеками для React", //Coincurrent библиотека графика Chart.js
    "Redux, axios, useEffect", // переписываем запросы для redux
    "Login (авторегистрация)", // аторегистрация для редакс
    "библиотека localforage для Redux", // делаем избраное для Coin
    "Создаем чат между пользователями часть 1",
    "Создаем чат между пользователями часть 2",
    "Создаем чат между пользователями часть 3",
    "Работа над ошибками",
    "Основы NodeJS",
    "Node.js core",
    "События. EventEmitter",
    "Модули. NPM",
    "Работа с файлами. Потоки и асинхронность",
    "TCP, HTTP и HTTPS серверы",
    "Web сокеты и модуль ws. Socket.io",
    "Асинхронный поток. Модуль Async",
    "Node.js и Mongo.db",
    "Шаблонизаторы. Mustache, Jade, EJS",
    "Веб-каркас для Node.js",
    "Тестирование кода на Node.js",
    "Работа над ошибками (создание резюме для работы)"
    
]

const Redux = [
    "Вспоминаем основы React (Git)",  //пишем todolist
    "Знакомство с Redux (mapStateToProps)", //переписываем в редакс
    "action for Redux", // функции для редакс
    "react router dom, HOC, REST API", //Coin и запросы 
    "Знакомство с разными библиотеками для React", //Coincurrent библиотека графика Chart.js
    "Redux, axios, useEffect", // переписываем запросы для redux
    "Login (авторегистрация)", // аторегистрация для редакс
    "библиотека localforage для Redux", // делаем избраное для Coin
    "Создаем чат между пользователями часть 1",
    "Создаем чат между пользователями часть 2",
    "Создаем чат между пользователями часть 3",
    "Работа над ошибками (создание резюме для работы)",
    // Кр сделать компоненту настройки
]

const ReactRedux = [
    "Вспоминаем основы js (Git)",
    "Regex",
    'Замыкание и Рекурсия',
    "This, apply,call,bind, proto, prototype",
    "class, constructor, cuper",
    "работа с  Api (асинхронный код)",
    "Знакомство с React (насройка окружения)",
    "React компоненты и props",
    "Первый хук, useState",
    "useMemo",
    "react router dom (Начинаем первый проект, пишем свою социальная сеть)",
    "useEffect и axios",
    "HOC",
    "useContext",
    "Знакомство с разными библиотеками для React",
    "Login (авторегистрация)",
    "Взаимодействие разных аккаунтов вашей соц сети",
    "Отправка локальных фото в сеть (axios post,put...)",
    "Создаем чат между пользователями часть 1",
    "Создаем чат между пользователями часть 2",
    "Создаем чат между пользователями часть 3",
    "Работа над ошибками (создание резюме для работы)",
    "Работа над ошибками",
    "Знакомство с Redux (mapStateToProps)", //переписываем в редакс
    "action for Redux", // функции для редакс
    "react router dom, HOC, REST API", //Coin и запросы 
    "Знакомство с разными библиотеками для React", //Coincurrent библиотека графика Chart.js
    "Redux, axios, useEffect", // переписываем запросы для redux
    "Login (авторегистрация)", // аторегистрация для редакс
    "библиотека localforage для Redux", // делаем избраное для Coin
    "Создаем чат между пользователями часть 1",
    "Создаем чат между пользователями часть 2",
    "Создаем чат между пользователями часть 3",
    "Работа над ошибками (создание резюме для работы)",

]
const python = [
    "Основы python",
    "Переменные, выражения и инструкции Python",
    "Управление потоком выполнения",
    "Итерации",
    "Функции и модули",
    "Строки",
    "Основы работы с системой контроля версий",
    "Файлы",
    "Коллекции",
    "Элементы функционального программирования",
    "Функции",
    "Объектно-ориентированный подход",
    "Управление созданием экземпляров класса",
    "Приемы объектно-ориентированного программирования",
    "Модули и пакеты",
    "Работа с файлами",
    "Встроенные пакеты Python",
    "Networking",
    "Многопоточность в Python",
    "Процессы в Python",
    "Асинхронное программирование",
    "Работа с СУБД SQLite, PostgreSQL",
    "Object Relational Mapping",
    "NoSQL-базы данных",
    "Веб-разработка",
    "Работа над ошибками (создание резюме для работы)",
  
]
const java = [
    'Общая характеристика языка Java',
    "Типы данных и основные операции с ними",
    "Поток управления",
    "Массивы",
    "Строки",
    "GIT. Контроль версии",
    "Введение в объектно-ориентированное программирование",
    "Отношения между объектами",
    "Наследование и полиморфизм",
    "Класс Object",
    "Внутренние классы",
    "Перечисление",
    "Работа с базами данных",
    "Обработка ошибок и исключения",
    "Система ввода-вывода",
    "Desktop-приложения",
    "Классы коллекций",
    "Знакомство с XML",
    "Многопоточность",
    "Классы BigInteger и BigDecimal",
    "Универсальные типы",
    "Утилитные пакеты",
    "Java 8. Анонимные функции. Stream API",
    "Автоматизация составления Java-проектов", //POTOM cr
    "Java annotations",
    "Java reflection",
    "Advanced generics",
    "Advanced collections",
    "Advanced multithreading / concurrency",
    "Advanced OOP",
    "Design patterns",
    "JRE security, JVM internals",
    "Desktop-приложения: технология JavaFX",
    "Spring",
    "Работа с XML и JSON",
    "Введение в SQL",
    "JDBC",
    "Знакомство с Lombok и Log4J",
    "Работа над ошибками (создание резюме для работы)",
]

const NodeJS = [
    "Основы NodeJS",
    "Node.js core",
    "События. EventEmitter",
    "Модули. NPM",
    "Работа с файлами. Потоки и асинхронность",
    "TCP, HTTP и HTTPS серверы",
    "Web сокеты и модуль ws. Socket.io",
    "Асинхронный поток. Модуль Async",
    "Node.js и Mongo.db",
    "Шаблонизаторы. Mustache, Jade, EJS",
    "Веб-каркас для Node.js",
    "Тестирование кода на Node.js",
    "Работа над ошибками (создание резюме для работы)"
]
const list_Our_Courses = [{
        page : 'HTMLcss.html',
        id: id(),
        title: "HTML и CSS для JavaScript",
        text: "Планируете изучать JavaScript? Вам необходимо знание HTML и CSS, поскольку большая часть технологий JavaScript это манипуляции со страницей! Курс изучает современную верстку и позволяет быстро научится создавать сайты. В курсе рассмотрены все основные технологии HTML5 и CSS3",
        img: "./assest/img/course/Html_Css2.jpg",
        start: "5.01.2021",
        price: {
            uan_one: 3500,
            uan_max: 3500,
            rub_one: 2,
            rub_max: 4,
            $_one: 125,
            $_max: 125,
        },
        duration: {
            number_of_lessons: HTML_CSS.length,
            hours: HTML_CSS.length*2,
            months: 1,
            quanity_per_week: 3,
            duration_one_lesson : 2
        },
        plan: HTML_CSS
    },
    {
        page : 'FrontEnd.html',
        id: id(),
        title: "Front-End с нуля до первой работы",
        text: "Front-End —это дизайнер, верстальщик и программист в одном лице.  В наше время, пожалуй, быстрее всего развивающаяся область программирования.  С другой стороны, эти технологии достаточно устоявшиеся и распространены практически повсеместно, ведь браузер есть во многих электронных устройствах.",
        img: "./assest/img/course/front_end.jpg",
        start: "5.12.2020",
        price: {
            uan_one: 3400,
            uan_max: 12000,
            uan_discount :19500,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 425,

        },
        duration: {
            number_of_lessons: FrontEnd.length,
            hours: FrontEnd.length*2,
            months: 3.5,
            quanity_per_week:3,
            duration_one_lesson : 2
        },
        plan: FrontEnd
    },
    {
        page : 'Js.html',
        id: id(),
        title: "JavaScript для Front-end",
        text: "Начните писать программы на JavaScript. Курс рассчитан на тех, кто начинает с нуля. Шаблоны и подобранные задачи по нарастанию сложности помогут вам создавать корректный код. В курсе представлены все темы, необходимые для соискания уровня junior разработчика",
        img: "./assest/img/course/js3.jpg",
        start: "5.01.2021",
        price: {
            uan_one: 5400,
            uan_max: 5400,
            uan_discount :8200,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 285,
        },
        duration: {
            number_of_lessons: JS.length,
            hours: JS.length*2,
            months: 1,
            quanity_per_week: 2,
            duration_one_lesson : 2
        },
        plan: JS
    },
    // //!
    // {
    //     page : 'JsAdvanse.html',
    //     id: id(),
    //     title: "JavaScript для Front-end Advansed",
    //     text: "Начните писать программы на JavaScript. Курс рассчитан на тех, кто начинает с нуля. Шаблоны и подобранные задачи по нарастанию сложности помогут вам создавать корректный код. В курсе представлены все темы, необходимые для соискания уровня junior разработчика",
    //     img: "./assest/img/course/js3.jpg",
    //     start: "5.01.2021",
    //     price: {
    //         uan_one: 7600,
    //         uan_max: 7600,
    //         uan_discount :11100,
    //         rub_one: 2,
    //         rub_max: 4,
    //         $_one: 2,
    //         $_max: 285,
    //     },
    //     duration: {
    //         number_of_lessons: 19,
    //         hours: 38,
    //         months: 2,
    //         quanity_per_week: 3,
    //         duration_one_lesson : 2
    //     },
    // },
    // //?
    {
        page : 'ReactRedux.html',
        id: id(),
        title: "React + Redux",
        text: "Учим самый популярный фреймворк JavaScript – React. Курс подходит для тех, кто хочет освоить фреймворк React и делать приложения любого уровня сложности совместно с движком Redux который позволяет писать бизнес логику",
        img: "./assest/img/course/RR.jpg",
        start: "5.02.2021",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 355,
        },
        duration: {
            number_of_lessons: ReactRedux.length,
            hours: ReactRedux.length*2,
            months: 2,
            quanity_per_week: 2,
        },
        plan: ReactRedux
    },
    {
        page : 'Python.html',   
        id: id(),
        title: "Python",
        text: "Python входит в топ-10 самых востребованных языков программирования. Он открывает путь в топовые IT-компании: Google, Pixar, Youtube, Instagram, Nasa, Intel, Pinterest используют именно его. После курса вы сможете устроиться в компанию, где создают интерактивные веб-сервисы на Python, а таких очень много: 3305 вакансий для python-разработчика открыто прямо сейчас",
        img: "./assest/img/course/python-logo.jpg.jfif",
        start: "Уже нет мест",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 500,
        },
        duration: {
            number_of_lessons: python.length,
            hours: python.length*2,
            months: 2,
            quanity_per_week: 2,
        },
        plan: python
    },
    {
        page : 'Java.html',  
        id: id(),
        title: "Java",
        text: "Этот популярный язык имеет множество сфер применения: от создания динамических элементов на сайтах до организации сбора информации о пользователях интернет-магазинов. Программист Java также занимается улучшением дизайна и функциональности сайтов, тестированием работы приложений.",
        img: "./assest/img/course/java-logo.jpg",
        start: "В скором времени",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 500,
        },
        duration: {
            number_of_lessons: java.length,
            hours: java.length*2,
            months: 2,
            quanity_per_week: 2,
        },
        plan: java
    },
    // {
    //     id: id(),
    //     title: "C#",
    //     text: "Курс предназначен для тех, кто только начинает свой путь в IT-индустрии и не имеет представления о основах программирования и В какой специальности развиваться. В течение двух месяцев вы узнаете как устроенной компьютер, как писать на языке C # (.Net), которые являются переменные, типы данных и многое другое.",
    //     img: "./assest/img/course/C-logo.png",
    //     start: "В скором времени",
    //     price: {
    //         uan_one: 3500,
    //         uan_max: 12000,
    //         rub_one: 2,
    //         rub_max: 4,
    //         $_one: 2,
    //         $_max: 500,
    //     },
    //     duration: {
    //         number_of_lessons: 16,
    //         hours: 50,
    //         months: 2,
    //         quanity_per_week: 2,
    //     },
    // },
    {
        page : 'NodeJS.html', 
        id: id(),
        title: "NodeJS (Back-end)",
        text: "Node.js представляет среду выполнения кода на JavaScript, которая построена на основе движка JavaScript Chrome V8, который позволяет транслировать вызовы на языке JavaScript в машинный код. Node.js прежде всего предназначен для создания серверных приложений на языке JavaScript. Хотя также существуют проекты по написанию кода для микроконтроллеров.",
        img: "./assest/img/course/Node2.jpg",
        start: "В скором времени",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 635,
        },
        duration: {
            number_of_lessons: NodeJS.length,
            hours: NodeJS.length*2,
            months: 4,
            quanity_per_week: 1,
        },
        plan: NodeJS
    },
    //////////////!
    {
        page : 'Redux.html', 
        id: id(),
        title: "Redux технологии",
        text: "Redux — это официальный способ управлять состоянием в нетривиальных React приложениях. Несмотря на свою простоту и элегантность, он требует время на вникание. Кроме того, вокруг Redux огромная экосистема библиотек, автоматизирующих разные задачи. Этот курс посвящен в том числе самым популярным библиотекам.",
        img: "./assest/img/course/redux.png",
        start: "В скором времени",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 635,
        },
        duration: {
            number_of_lessons: Redux.length,
            hours: Redux.length*2,
            months: 4,
            quanity_per_week: 1,
        },
        plan: Redux
    },
    {
        page : 'FullStack.html', 
        id: id(),
        title :'Full Stack Developer',
        text: " FullStack программист совмещает в себе знания Front-End и Backend. Такие специалисты пользуются большим спросом на рынке труда и даже на старте претендуют на высокие зарплаты.",
        img: "./assest/img/course/full-stack-developer.jpg",
        start: "В скором времени",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 635,
        },
        duration: {
            number_of_lessons: FullStack.length,
            hours: FullStack.length*2,
            months: 4,
            quanity_per_week: 1,
        },
        plan: FullStack
    },
    {
        page : 'CSS.html', 
        id: id(),
        title: "Полный курс CSS", // до первой работы
        text: `Пока HTML определяет содержимое веб-страницы, CSS занимается её стилизацией. Это подразумевает настройку цвета, шрифтов, размеров, полей, положения элементов веб-страницы.
        HTML инертный. CSS изменчивый.
        CSS приносит на сайт жизнь путём нанесения слоя краски на статичное содержимое и повышает его назначение через цвет, пространство, акцент и движение.`,
        img: "./assest/img/course/cssClassic.jpeg",
        start: "В скором времени",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 635,
        },
        duration: {
            number_of_lessons: CSS_simple.length,
            hours: CSS_simple.length*2,
            months: 4,
            quanity_per_week: 1,
        },
        plan: CSS_simple
    },
    {
        page : 'React.html', 
        id: id(),
        title:'Уникальная React технология',
        text: "Учим самый популярный фреймворк JavaScript – React. Курс подходит для тех, кто хочет освоить фреймворк React и делать приложения любого уровня сложности.Последнее время знание React является обязательным для frontend разработчика и решающим при приеме на работу. ",
        img: "./assest/img/course/React.jpg",
        start: "В скором времени",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 635,
        },
        duration: {
            number_of_lessons: React.length,
            hours: React.length*2,
            months: 4,
            quanity_per_week: 1,
        },
        plan: React
    },
    {
        page : 'CSSanimation.html', 
        id: id(),
        title: "Курс CSS анимации",
        text: "Рассмотрим основы анимации на CSS. Нам предстоит пройти путь развития цивилизации и покорить космический простор. Мы будем двигать, поворачивать и видоизменять объекты, попутно осваивая приёмы работы анимации в CSS.",
        img: "./assest/img/course/cssAnim.jpg",
        start: "В скором времени",
        price: {
            uan_one: 3500,
            uan_max: 12000,
            rub_one: 2,
            rub_max: 4,
            $_one: 2,
            $_max: 635,
        },
        duration: {
            number_of_lessons: CSSAdvanced.length,
            hours: CSSAdvanced.length*2,
            months: 4,
            quanity_per_week: 1,
        },
        plan: CSSAdvanced
    },
];